# Site settings
title: My Awesome Website
description: >-
  This is my personal website where I share my projects and blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://<username>.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-cayman

# Author settings
author:
  name: Dylan Joshua B. Cablayan
  email: dylanj7@.hawaii.edu

# Navigation links
header_pages:
  - index.md
  - about.md
  - blog.md

# Plugins
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
